Fix invocation with latest @google-cloud/pubsub (0.20.0) (#10)
- Fix: TypeError: Class constructor PubSub cannot be invoked without 'new'
- instantiate @google-cloud/pubsub only if we need to create topics
- Removed bluebird, since Promises are supported since node 6.
- Fix unit tests
- latest PubSub client tries to modify ack deadline after 10 seconds, so increase timeouts in unit tests.

Error:
```
  console.error node_modules/jest-jasmine2/build/jasmine/Env.js:157
    Unhandled error

  console.error node_modules/jest-jasmine2/build/jasmine/Env.js:158
    TypeError: Class constructor PubSub cannot be invoked without 'new'
        at PubSubEmulator.startSuccessListener (xxx/node_modules/google-pubsub-emulator/src/pubsub-emulator.js:60:59)
        at emitOne (events.js:116:13)
        at PubSubStateEmitter.emit (events.js:211:7)
        at PubSubEmulator._setState (xxx/node_modules/google-pubsub-emulator/src/pubsub-emulator.js:209:24)
        at PubSubEmulator._processStd (xxx/node_modules/google-pubsub-emulator/src/pubsub-emulator.js:156:12)
        at PubSubEmulator._emulatorStdErrListener (xxx/node_modules/google-pubsub-emulator/src/pubsub-emulator.js:255:10)
        at emitOne (events.js:116:13)
        at Socket.emit (events.js:211:7)
        at addChunk (_stream_readable.js:263:12)
        at readableAddChunk (_stream_readable.js:250:11)
        at Socket.Readable.push (_stream_readable.js:208:10)
        at Pipe.onread (net.js:597:20)
```